### ISSUE TITLE
Отсутствует поле df['effectiveyield']

### ISSUE THREAD

**Issue by greg-kan** [AzzraelCode/moex-bonds#1]
Здравствуйте.

При попытке запустить код, в файле Analytics.py ругается на отсутствие поля effectiveyield в этой строке:

'с доходностью > 1%' : len(df[ df['effectiveyield'] >= 1].index),

В таблице, судя по Models.py, такое поле не определено.

**Comment by AzzraelCode** [comment]
Этому коду уж года три как ;) Он полностью устарел...

**Comment by greg-kan** [comment]
Ну, API MOEX особо не поменялся, насколько я вижу.
Я только начал с этим разбираться и мне нужен скринер облигаций и акций.

Так как я не знаю, чем принято пользоваться, я решил написать свой ))
Тем более, что это, я надеюсь, поможет разобраться в сути вопроса.

Если Вы можете подсказать, что можно использовать для сбора данных в локальную БД и анализа, подскажите, пожалуйста.

Извиняюсь, что пишу сюда )

И спасибо Вам за материалы, в любом случае!
